### PR TITLE
[DO NOT MERGE] Play with NUI

### PR DESCRIPTION
**Pull request by MunifTanjim**
I don't intend this PR to get merged.

I'm just playing around to see if `nui.nvim`'s `tree` block has got everything covered for real world usage.

### CODE REVIEW

**Comment by Uzaaft** [comment]
Out of curiousity: Who do you open up a draft PR if you do not intend for it to be merged?

**Comment by MunifTanjim** [comment]
> Out of curiousity: Who do you open up a draft PR if you do not intend for it to be merged?

Hmm... 🤔 Didn't really think about that. But if somebody ask question about a similar use-case I can now point them to this PR...

Not sure where you're coming from, but I don't see any harm in doing this (unless the maintainer is annoyed with it) 🤷🏼‍♂️

**Comment by Uzaaft** [comment]
Having a PR open just to have a PR is not useful at all. If you were going to end up actually contributing to the project it would have been useful. It just a waste of the contributors time.

**Comment by MunifTanjim** [comment]
I'm still don't get why you're being so negative. But alrighty! Sorry for wasting your time man. 😂 (I thought I'm the one wasting my time playing around with stuffs.)

_If the maintainer or other contributor wants to replace the UI with an external library (no reason for doing so, very little to gain), the codes will still be here. So even if I didn't intend this PR to get merged, doesn't mean it's not a contribution. Peace... ✌🏼_

**Pull request closed without merging**
