### PR TITLE
feat(telescope provider): (Smart) multiselect

### PR DESCRIPTION
**Pull request by runiq**
Adds support for Telescope's multiselect mode and smart select mode.

- Multiselect: Only the selected entries are shown in Trouble.
- Smart: If you have selected some entries, only those entries will be shown in Trouble. Otherwise all entries will be shown.

### CODE REVIEW

**Comment by folke** [comment]
Thanks man! I didn;t even know about the multi-select in Telescope. Super useful!

**Comment by Bruflot** [comment]
This PR breaks Trouble if you don't have Telescope installed. The calls to `require` fail since none of the modules exist. Perhaps add an option to conditionally include the provider? 

@folke

**Comment by runiq** [comment]
Oops, sorry for that! I'll add a check in a few minutes (on my way home right now).

**Comment by folke** [comment]
@Bruflot I just pushed a fix for this. It also gave issue when lazy-loading Telescope. Should be all fixed now!

**Comment by folke** [comment]
@runiq no worries, all fixed :) Thanks again for the PR!

**Pull request merged**
