### PR TITLE
feat: user can custom the format of diagnostic rendering

### PR DESCRIPTION
**Pull request by adoyle-h**

### CODE REVIEW

**Comment by adoyle-h** [comment]
@folke Could you review this PR? It has been waiting for one month.

**Comment by folke** [comment]
Thank you for the suggestion, but I'm not a fan of this. You can always just override the method yourself.

```lua

local renderer = require("trouble.renderer")

function renderer.render_diagnostics(view, text, items)
  -- add your custom code here
end
```

**Comment by adoyle-h** [comment]
@folke But the `signs` variable is [unexported](https://github.com/folke/trouble.nvim/blob/3b754285635a66a93aeb15fa71a23417d8997217/lua/trouble/renderer.lua#L10).
How to `local sign = diag.sign or signs[string.lower(diag.type)]` in my override `function renderer.render_diagnostics`?

**Comment by folke** [comment]
I just pushed a change that exposes `renderer.signs`

**Pull request closed without merging**
