### PR TITLE
Add multiline diagnostic support

### LINKED ISSUE #279: bug: two line error messages concatenated without space inbetween (Rust analyzer errors)
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Ubuntu 22.0

### Describe the bug

image

The actual diagnostic messages from rust analyzer contains 2 lines:

```
1: cannot borrow `producer` as mutable more than once at a time
second mutable borrow occurs here (rustc)
```

### Steps To Reproduce

1. neovim with rust analyzer set up. Create any errors that has two lines.

### Expected Behavior

At least a space should be introduced when the two lines are joined together.

### Repro

```Lua
don't think this is needed.
```

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #279, #268 and #11

A preview of how this looks:
image

### CODE REVIEW

**Comment by folke** [comment]
Thank you for this PR!

I'll look into it later today, but I think this potentially breaks actions and folds on the different lines. Maybe not though, need to check :)

**Comment by MariaSolOs** [comment]
> Thank you for this PR!
> 
> I'll look into it later today, but I think this potentially breaks actions and folds on the different lines. Maybe not though, need to check :)

Thanks to you! There are a couple of design questions in #279 but we should definitely first make sure this doesn’t break anything.

**Comment by eatgrass** [comment]
@MariaSolOs @folke 
please check the screenshot, I think keeping this first line in entry is more consistent
image

**Comment by folke** [comment]
I've made multiline configurable and changed the layout as @eatgrass suggested.
Still have to check if multline possibly breaks something

**Comment by folke** [comment]
All seems to work as it should. Merged. Thank you!

multiline is disabled by default, can be enabled with `opts.multiline = true`

**Comment by MariaSolOs** [comment]
> All seems to work as it should. Merged. Thank you!
> 
> 
> 
> Edit: made multiline the default

Thanks to you! I hope people like the new layout as much as I do ☺️

**Comment by kting28** [comment]
Thanks @MariaSolOs

**Pull request merged**
