### PR TITLE
docs: add filter examples and documentations

### PR DESCRIPTION
**Pull request by b0ae989c**
See #473. All inputs are welcome!

Work in progress. Do not merge.

### CODE REVIEW

**Comment by folke** [comment]
This is great already!

Would be good to also add a section to the readme with a link to this doc.

I'm fine with merging this in the current state.
You can always make an additional PR if you want with some updates.

Thank you!

**Comment by b0ae989c** [comment]
Got it. I'm adding the readme link.

**Comment by b0ae989c** [comment]
Ready. @folke

**Comment by folke** [comment]
Thanks!

**Pull request merged**
