### PR TITLE
feat: add wrap config option for trouble buffer

### PR DESCRIPTION
**Pull request by roobert**
As popularly requested [here](https://github.com/folke/trouble.nvim/issues/114).

There doesn't seem to be a viable workaround using autocmd so I think a config option is the only option here..

Thanks for the awesome plugin!

### CODE REVIEW

**Comment by Zajozor** [comment]
Works great, thanks @roobert , I tested this locally.

@folke I know you're an extremely busy man, but if you have a minute to glance at this, it would be amazing 🙏🏻 
(I'm aware of the "K" hover functionality, however wrap is just more glancable)

**Comment by tummetott** [comment]
@roobert you forgot to update the vimdoc

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev

`opts.win.wo.wrap = true`

**Comment by carlesandres** [comment]
For the record. This is how it's done in v3:

```lua
    {
        "folke/trouble.nvim",
        dependencies = { "nvim-tree/nvim-web-devicons" },
        opts = {
            win = {
                wo = {
                    wrap = true,
                },
            },
        },
    },
```

**Pull request closed without merging**
