### PR TITLE
Remove useless "no results" notification

### LINKED ISSUE #154: remove completely or suppress (via a setting) the "no results" notification
When there are no results to display, trouble tells nvim to output a warning notification that there are "no results":
https://github.com/folke/trouble.nvim/blob/main/lua/trouble/renderer.lua#L49-L51

This doesn't seem at all necessary to me, since if there are no results, it is obvious since the window is empty. It is especially annoying to get that notification if one is using the https://github.com/rcarriga/nvim-notify plugin, since it will always pop up a "no results" warning window every time you go to a buffer that has no diagnostic problems (as long as the trouble window is visible).

If there is a good reason to keep the "no results" notification, can we please have a trouble setting where we can disable / suppress the notification if we so desire?  Thank you!

### PR DESCRIPTION
**Pull request by bellini666**
Fix #154

### CODE REVIEW

**Comment by callumacrae** [comment]
yes please!!

**Comment by ADawesomeguy** [comment]
Is there any update on this? I would really appreciate if it were to be fixed!

**Comment by qianlifeng** [comment]
pls merge this!!

**Comment by errantepiphany** [comment]
@folke Can this please be merged?

**Comment by qianlifeng** [comment]
Glad to see it get merged, thx 👍🏻

**Comment by ADawesomeguy** [comment]
YAY thank you

**Pull request merged**
